[build]
  # now runs `next build` **and** `next export`
  command = "npm run build && npm run export"
  publish = "out"

# Remove the @netlify/plugin-nextjs plugin block entirely 
# (we’re doing a full static export instead)

# 1) Redirect /admin → /admin/ (trailing slash)
[[redirects]]
  from   = "/admin"
  to     = "/admin/"
  status = 301

# 2) Serve the real config.yml
[[redirects]]
  from   = "/admin/config.yml"
  to     = "/admin/config.yml"
  status = 200

# 3) Everything else under /admin is your SPA
[[redirects]]
  from   = "/admin/*"
  to     = "/admin/index.html"
  status = 200
  force  = true
