[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 1) Always redirect /admin to /admin/
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# 2) Serve config.yml as-is
[[redirects]]
  from = "/admin/config.yml"
  to = "/admin/config.yml"
  status = 200

# 3) Then the SPA shell for everything else under /admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true 